export enum CardFormat {
    Standard = "Standard",
    Future = "Future",
    Historic = "Historic",
    Timeless = "Timeless",
    Gladiator = "Gladiator",
    Pioneer = "Pioneer",
    Explorer = "Explorer",
    Modern = "Modern",
    Legacy = "Legacy",
    Pauper = "Pauper",
    Vintage = "Vintage",
    Penny = "Penny",
    Commander = "Commander",
    Oathbreaker = "Oathbreaker",
    Standardbrawl = "Standardbrawl",
    Brawl = "Brawl",
    Alchemy = "Alchemy",
    Paupercommander = "Paupercommander",
    Duel = "Duel",
    Oldschool = "Oldschool",
    Premodern = "Premodern",
    Predh = "Predh"
}