export interface CardDto {
  object: string;
  id: string;
  oracle_id: string;
  multiverse_ids: number[];
  mtgo_id: number;
  arena_id: number;
  tcgplayer_id: number;
  cardmarket_id: number;
  name: string;
  lang: string;
  released_at: string;
  uri: string;
  scryfall_uri: string;
  layout: string;
  highres_image: boolean;
  image_status: string;
  image_uris: {
    small: string;
    normal: string;
    large: string;
    png: string;
    art_crop: string;
    border_crop: string;
  };
  mana_cost: string;
  cmc: number;
  type_line: string;
  oracle_text: string;
  power: string;
  toughness: string;
  colors: string[];
  color_identity: string[];
  keywords: string[];
  legalities: {
    standard: "legal" | "not_legal";
    future: "legal" | "not_legal";
    historic: "legal" | "not_legal";
    timeless: "legal" | "not_legal";
    gladiator: "legal" | "not_legal";
    pioneer: "legal" | "not_legal";
    explorer: "legal" | "not_legal";
    modern: "legal" | "not_legal";
    legacy: "legal" | "not_legal";
    pauper: "legal" | "not_legal";
    vintage: "legal" | "not_legal";
    penny: "legal" | "not_legal";
    commander: "legal" | "not_legal";
    oathbreaker: "legal" | "not_legal";
    standardbrawl: "legal" | "not_legal";
    brawl: "legal" | "not_legal";
    alchemy: "legal" | "not_legal";
    paupercommander: "legal" | "not_legal";
    duel: "legal" | "not_legal";
    oldschool: "legal" | "not_legal";
    premodern: "legal" | "not_legal";
    predh: "legal" | "not_legal";
  };
  games: string[];
  reserved: boolean;
  foil: boolean;
  nonfoil: boolean;
  finishes: string[];
  oversized: boolean;
  promo: boolean;
  reprint: boolean;
  variation: boolean;
  set_id: string;
  set: string;
  set_name: string;
  set_type: string;
  set_uri: string;
  set_search_uri: string;
  scryfall_set_uri: string;
  rulings_uri: string;
  prints_search_uri: string;
  collector_number: string;
  digital: boolean;
  rarity: string;
  card_back_id: string;
  artist: string;
  artist_ids: string[];
  illustration_id: string;
  border_color: string;
  frame: string;
  security_stamp: string;
  full_art: boolean;
  textless: boolean;
  booster: boolean;
  story_spotlight: boolean;
  edhrec_rank: number;
  penny_rank: number;
  preview: {
    source: string;
    source_uri: string;
    previewed_at: string;
  };
  prices: {
    usd: string | null;
    usd_foil: string | null;
    usd_etched: string | null;
    eur: string | null;
    eur_foil: string | null;
    tix: string | null;
  };
  related_uris: {
    gatherer: string;
    tcgplayer_infinite_articles: string;
    tcgplayer_infinite_decks: string;
    edhrec: string;
  };
  purchase_uris: {
    tcgplayer: string;
    cardmarket: string;
    cardhoarder: string;
  };
}
